name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Setup .NET 2.2
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '2.2.x'
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: 'Test report'
        path: '**/*.trx'
        reporter: 'dotnet-trx'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Package 
      run: dotnet pack -c Release --no-build -o nupkgs
      if: startsWith(github.ref, 'refs/tags/')
    - name: Push to Nuget
      run: dotnet nuget push "./nupkgs/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGETPUBLISHKEY }}
      if: startsWith(github.ref, 'refs/tags/')
